version: "3.9"

services:
  monitoring_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: monitoring-app:latest
    container_name: monitoring_app
    ports:
      - "8000:8000"
      - "3000:3000"
    environment:
      METRICS_STORAGE_LIMIT: 30
      METRICS_UPDATE_INTERVAL: 5
      API_POLLING_INTERVAL: 3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
