services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: ""
    image: monitoring-backend:dev
    container_name: monitoring_backend
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["gunicorn","--config", "gunicorn_config.py", "app:create_app()"]
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: monitoring-frontend:dev
    container_name: monitoring_frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
    depends_on:
      - backend
