[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*

testpaths = tests

markers =
    integration: Integration tests (require Docker)
    slow: Slow tests
    performance: Performance tests

addopts = 
    -v
    --tb=short
    --strict-markers

log_cli = false

# Running test - first pip install -r requirements.txt then type pytest in terminal 
# For cleaning the cache: python -c "import shutil; shutil.rmtree('.pytest_cache', ignore_errors=True); shutil.rmtree('tests/__pycache__', ignore_errors=True)"
# To generate coverage report, use: pytest --cov=app tests/
# or python -m pytest tests/ -v
# in case only want to run integration tests: python -m pytest tests/integration -v -m integration